name: Pubblish documentation on github pages

on:
  pull_request:
    brances:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8 
      - name: Install dependencies
        run:  pip install -r requirements.txt

      - run: pdoc ./src/API/yaml_wrapper.py -o ./docs

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.PUBLISH_DOCS }}
          publish_dir: ./docs