name: Pubblish documentation on github pages

on:
  pull_request:
    brances:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8 
      - name: Install dependencies
        run:  pip install -r requirements.txt

      - run: mkdir docs; pdoc --html --output-dir docs src.API

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs